In [3]:
import pandas as pd
import numpy as np
import panel as pn
pn.extension('tabulator')

import hvplot.pandas

In [5]:
# df = pd.read_csv("https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv")

In [6]:
# cache data to improve dashboard performance
if 'data' not in pn.state.cache.keys():

    df = pd.read_csv('https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv')

    pn.state.cache['data'] = df.copy()

else: 

    df = pn.state.cache['data']

In [8]:
df

,iso_code,country,year,co2,co2_per_capita,trade_co2,cement_co2,cement_co2_per_capita,coal_co2,coal_co2_per_capita,...,ghg_excluding_lucf_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
0,AFG,Afghanistan,1949,0.015,0.002,NaN,NaN,NaN,0.015,0.002,...,NaN,NaN,NaN,NaN,NaN,7624058.0,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1950,0.084,0.011,NaN,NaN,NaN,0.021,0.003,...,NaN,NaN,NaN,NaN,NaN,7752117.0,9.421400e+09,NaN,NaN,NaN
2,AFG,Afghanistan,1951,0.092,0.012,NaN,NaN,NaN,0.026,0.003,...,NaN,NaN,NaN,NaN,NaN,7840151.0,9.692280e+09,NaN,NaN,NaN
3,AFG,Afghanistan,1952,0.092,0.012,NaN,NaN,NaN,0.032,0.004,...,NaN,NaN,NaN,NaN,NaN,7935996.0,1.001732e+10,NaN,NaN,NaN
4,AFG,Afghanistan,1953,0.106,0.013,NaN,NaN,NaN,0.038,0.005,...,NaN,NaN,NaN,NaN,NaN,8039684.0,1.063052e+10,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25186,ZWE,Zimbabwe,2016,10.738,0.765,1.415,0.639,0.046,6.959,0.496,...,2.076,11.50,0.820,6.21,0.443,14030338.0,2.096179e+10,47.5,3385.574,1.889
25187,ZWE,Zimbabwe,2017,9.582,0.673,1.666,0.678,0.048,5.665,0.398,...,2.023,11.62,0.816,6.35,0.446,14236599.0,2.194784e+10,NaN,NaN,NaN
25188,ZWE,Zimbabwe,2018,11.854,0.821,1.308,0.697,0.048,7.101,0.492,...,2.173,11.96,0.828,6.59,0.456,14438812.0,2.271535e+10,NaN,NaN,NaN
25189,ZWE,Zimbabwe,2019,10.949,0.748,1.473,0.697,0.048,6.020,0.411,...,NaN,NaN,NaN,NaN,NaN,14645473.0,NaN,NaN,NaN,NaN
25190,ZWE,Zimbabwe,2020,10.531,0.709,NaN,0.697,0.047,6.257,0.421,...,NaN,NaN,NaN,NaN,NaN,14862927.0,NaN,NaN,NaN,NaN

In [9]:
df[df['country'] == 'South America']

,iso_code,country,year,co2,co2_per_capita,trade_co2,cement_co2,cement_co2_per_capita,coal_co2,coal_co2_per_capita,...,ghg_excluding_lucf_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
20731,NaN,South America,1884,0.004,0.001,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,30121017.0,NaN,NaN,NaN,NaN
20732,NaN,South America,1885,0.004,0.001,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,30717090.0,NaN,NaN,NaN,NaN
20733,NaN,South America,1886,0.007,0.002,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,31328092.0,NaN,NaN,NaN,NaN
20734,NaN,South America,1887,1.092,0.173,NaN,NaN,NaN,1.085,0.172,...,NaN,NaN,NaN,NaN,NaN,31954600.0,NaN,NaN,NaN,NaN
20735,NaN,South America,1888,0.898,0.139,NaN,NaN,NaN,0.890,0.138,...,NaN,NaN,NaN,NaN,NaN,32597223.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20863,NaN,South America,2016,1164.898,2.799,75.198,44.571,0.107,118.252,0.284,...,NaN,NaN,NaN,NaN,NaN,416164871.0,NaN,NaN,NaN,NaN
20864,NaN,South America,2017,1156.734,2.755,81.886,43.588,0.104,117.181,0.279,...,NaN,NaN,NaN,NaN,NaN,419903920.0,NaN,NaN,NaN,NaN
20865,NaN,South America,2018,1091.450,2.577,82.401,42.815,0.101,113.132,0.267,...,NaN,NaN,NaN,NaN,NaN,423581098.0,NaN,NaN,NaN,NaN
20866,NaN,South America,2019,1065.510,2.494,74.228,42.923,0.100,110.108,0.258,...,NaN,NaN,NaN,NaN,NaN,427199425.0,NaN,NaN,NaN,NaN
20867,NaN,South America,2020,994.160,2.308,NaN,43.644,0.101,107.338,0.249,...,NaN,NaN,NaN,NaN,NaN,430759771.0,NaN,NaN,NaN,NaN